train:
  _target_: src.datasets.WeatherDataset
  dataset_dir: /home/andrewut/data
  data_start: 74512
  data_end: 86200
val:
  _target_: src.datasets.WeatherDataset
  dataset_dir: /home/andrewut/data
  data_start: 86201
  data_end: 87660
# test:
#   _target_: src.datasets.WeatherDataset
#   two_m_temperature_path: /home/andrewut/data/2m_temperature_data.npy
#   ten_m_u_component_of_wind_path: /home/andrewut/data/10m_u_component_of_wind_data.npy
#   ten_m_v_component_of_wind_path: /home/andrewut/data/10m_v_component_of_wind_data.npy
#   mean_sea_level_pressure_path: /home/andrewut/data/mean_sea_level_pressure_data.npy
#   geopotential_path: /home/andrewut/data/geopotential_data.npy
#   v_component_of_wind_path: /home/andrewut/data/v_component_of_wind_data.npy
#   u_component_of_wind_path: /home/andrewut/data/u_component_of_wind_data.npy
#   specific_humidity_path: /home/andrewut/data/specific_humidity_data.npy
#   data_start: 87600
#   data_end: 89060
