train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.MseMetric
    name: "MseMetric" # it is better to avoid spaces in names
  - _target_: src.metrics.MaeMetric
    name: "MaeMetric"
  - _target_: src.metrics.RmseMetric
    name: "RmseMetric"
